[project]
name = "queue-reactive"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "altair>=6.0.0",
    "ipykernel>=7.1.0",
    "jupyter>=1.1.1",
    "jupyter-black>=0.4.0",
    "matplotlib>=3.10.7",
    "numpy>=2.3.5",
    "polars>=1.35.2",
    "scienceplots>=2.2.0",
    "scipy>=1.16.3",
    "seaborn>=0.13.2",
]
